# Generated by Django 4.2.10 on 2024-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.IntegerField(max_length=30, verbose_name="Telegram ID"),
                ),
                ("username", models.TextField(max_length=150, verbose_name="Username")),
                (
                    "first_name",
                    models.TextField(max_length=150, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.TextField(max_length=150, verbose_name="Last Name"),
                ),
                (
                    "access",
                    models.BooleanField(default=False, verbose_name="Доступ к боту"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.TextField(max_length=150, verbose_name="Торговая сеть")),
                ("bo", models.TextField(max_length=150, verbose_name="Образ сервера")),
                ("pos", models.TextField(max_length=150, verbose_name="Образ кассы")),
                ("sco", models.TextField(max_length=150, verbose_name="Образ КСО")),
                ("pc", models.TextField(max_length=150, verbose_name="Образ PC")),
            ],
        ),
        migrations.CreateModel(
            name="IPAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sap", models.TextField(max_length=10, verbose_name="SAP объекта")),
                (
                    "name",
                    models.TextField(
                        max_length=20, verbose_name="Наименование объекта"
                    ),
                ),
                ("ip_mag", models.TextField(verbose_name="IP адрес")),
                ("subnet_mag", models.TextField(verbose_name="Подсеть")),
            ],
        ),
    ]
