# Generated by Django 4.2.10 on 2024-02-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.TextField(
                max_length=150, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.TextField(max_length=150, null=True, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telegram_id",
            field=models.IntegerField(verbose_name="Telegram ID"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.TextField(max_length=150, null=True, verbose_name="Username"),
        ),
    ]
