# Generated by Django 4.2.10 on 2024-03-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("send_mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="send_message",
            field=models.BooleanField(
                default=False, verbose_name="Статус доставки пользователю"
            ),
        ),
    ]
