# Generated by Django 4.2.10 on 2024-03-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("send_mail", "0002_alter_item_send_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="subject",
            field=models.TextField(default=None, verbose_name="Тема письма"),
            preserve_default=False,
        ),
    ]
