# Generated by Django 4.2.10 on 2024-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("send_mail", "0003_item_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="uin",
            field=models.TextField(default="None", verbose_name="uin"),
        ),
    ]
