# Generated by Django 4.2.10 on 2024-03-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("send_mail", "0004_item_uin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="email_files/",
                verbose_name="Прикладываемый файл",
            ),
        ),
    ]
